default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Punj@1234
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: techinchargers_development

production:
  <<: *default
  database: techinchargers_development

